# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/hashicorp/terraform";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/terraform";
      rev = "785188983a1703be782142d46296e483421f1e1b";
      sha256 = "128y2ajgr6x3cp25mbwr0dq1p710vsjjbrscgd2yjkhqkiy7xgis";
    };
  }
]
